merged in changes from timers-rewrite branch
git-svn-id: https://gttr.svn.sourceforge.net/svnroot/gttr/trunk/gnotime@905 1e98219e-8636-0410-870a-f42bf3953145

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -899,6 +899,7 @@ MAINTAINER_MODE_FALSE
 MAINT
 YACC
 YFLAGS
+WARN_CFLAGS
 XMKMF
 X_CFLAGS
 X_PRE_LIBS
@@ -925,6 +926,8 @@ GCONF_SCHEMAS_INSTALL_TRUE
 GCONF_SCHEMAS_INSTALL_FALSE
 LIBQOF_CFLAGS
 LIBQOF_LIBS
+XSS_EXTENSION_CFLAGS
+XSS_EXTENSION_LIBS
 LIBDBUS_CFLAGS
 LIBDBUS_LIBS
 LIBGNOMEVFS_CFLAGS
@@ -980,6 +983,8 @@ LIBGLADE_CFLAGS
 LIBGLADE_LIBS
 LIBQOF_CFLAGS
 LIBQOF_LIBS
+XSS_EXTENSION_CFLAGS
+XSS_EXTENSION_LIBS
 LIBDBUS_CFLAGS
 LIBDBUS_LIBS
 LIBGNOMEVFS_CFLAGS
@@ -1578,6 +1583,9 @@ Optional Features:
   --disable-libtool-lock  avoid locking (might break parallel builds)
   --enable-maintainer-mode  enable make rules and dependencies not useful
 			  (and sometimes confusing) to the casual installer
+  --enable-compile-warnings=[no/minimum/yes/maximum/error]
+                          Turn on compiler warnings
+  --enable-iso-c          Try to warn if code is not ISO C
   --disable-glibtest      do not try to compile and run a test GLIB program
   --disable-schemas-install	Disable the schemas installation
 
@@ -1624,6 +1632,10 @@ Some influential environment variables:
   LIBQOF_CFLAGS
               C compiler flags for LIBQOF, overriding pkg-config
   LIBQOF_LIBS linker flags for LIBQOF, overriding pkg-config
+  XSS_EXTENSION_CFLAGS
+              C compiler flags for XSS_EXTENSION, overriding pkg-config
+  XSS_EXTENSION_LIBS
+              linker flags for XSS_EXTENSION, overriding pkg-config
   LIBDBUS_CFLAGS
               C compiler flags for LIBDBUS, overriding pkg-config
   LIBDBUS_LIBS
@@ -4736,7 +4748,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 4739 "configure"' > conftest.$ac_ext
+  echo '#line 4751 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7473,11 +7485,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7476: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7488: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7480: \$? = $ac_status" >&5
+   echo "$as_me:7492: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7763,11 +7775,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7766: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7778: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7770: \$? = $ac_status" >&5
+   echo "$as_me:7782: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7867,11 +7879,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7870: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7882: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:7874: \$? = $ac_status" >&5
+   echo "$as_me:7886: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -10229,7 +10241,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10232 "configure"
+#line 10244 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10329,7 +10341,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10332 "configure"
+#line 10344 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12749,11 +12761,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12752: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12764: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:12756: \$? = $ac_status" >&5
+   echo "$as_me:12768: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -12853,11 +12865,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12856: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12868: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:12860: \$? = $ac_status" >&5
+   echo "$as_me:12872: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14430,11 +14442,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14433: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14445: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14437: \$? = $ac_status" >&5
+   echo "$as_me:14449: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -14534,11 +14546,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14537: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14549: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14541: \$? = $ac_status" >&5
+   echo "$as_me:14553: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16734,11 +16746,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16737: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16749: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16741: \$? = $ac_status" >&5
+   echo "$as_me:16753: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -17024,11 +17036,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17027: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17039: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:17031: \$? = $ac_status" >&5
+   echo "$as_me:17043: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -17128,11 +17140,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17131: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17143: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:17135: \$? = $ac_status" >&5
+   echo "$as_me:17147: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -21728,7 +21740,138 @@ echo "${ECHO_T}no" >&6; }
 fi
 
 
-GNOME_COMPILE_WARNINGS
+
+
+    # Check whether --enable-compile-warnings was given.
+if test "${enable_compile_warnings+set}" = set; then
+  enableval=$enable_compile_warnings;
+else
+  enable_compile_warnings="yes"
+fi
+
+
+    warnCFLAGS=
+    if test "x$GCC" != xyes; then
+	enable_compile_warnings=no
+    fi
+
+    warning_flags=
+    realsave_CFLAGS="$CFLAGS"
+
+    case "$enable_compile_warnings" in
+    no)
+	warning_flags=
+	;;
+    minimum)
+	warning_flags="-Wall"
+	;;
+    yes)
+	warning_flags="-Wall -Wmissing-prototypes"
+	;;
+    maximum|error)
+	warning_flags="-Wall -Wmissing-prototypes -Wnested-externs -Wpointer-arith"
+	CFLAGS="$warning_flags $CFLAGS"
+	for option in -Wno-sign-compare; do
+		SAVE_CFLAGS="$CFLAGS"
+		CFLAGS="$CFLAGS $option"
+		{ echo "$as_me:$LINENO: checking whether gcc understands $option" >&5
+echo $ECHO_N "checking whether gcc understands $option... $ECHO_C" >&6; }
+		cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  has_option=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	has_option=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+		CFLAGS="$SAVE_CFLAGS"
+		{ echo "$as_me:$LINENO: result: $has_option" >&5
+echo "${ECHO_T}$has_option" >&6; }
+		if test $has_option = yes; then
+		  warning_flags="$warning_flags $option"
+		fi
+		unset has_option
+		unset SAVE_CFLAGS
+	done
+	unset option
+	if test "$enable_compile_warnings" = "error" ; then
+	    warning_flags="$warning_flags -Werror"
+	fi
+	;;
+    *)
+	{ { echo "$as_me:$LINENO: error: Unknown argument '$enable_compile_warnings' to --enable-compile-warnings" >&5
+echo "$as_me: error: Unknown argument '$enable_compile_warnings' to --enable-compile-warnings" >&2;}
+   { (exit 1); exit 1; }; }
+	;;
+    esac
+    CFLAGS="$realsave_CFLAGS"
+    { echo "$as_me:$LINENO: checking what warning flags to pass to the C compiler" >&5
+echo $ECHO_N "checking what warning flags to pass to the C compiler... $ECHO_C" >&6; }
+    { echo "$as_me:$LINENO: result: $warning_flags" >&5
+echo "${ECHO_T}$warning_flags" >&6; }
+
+    # Check whether --enable-iso-c was given.
+if test "${enable_iso_c+set}" = set; then
+  enableval=$enable_iso_c;
+else
+  enable_iso_c=no
+fi
+
+
+    { echo "$as_me:$LINENO: checking what language compliance flags to pass to the C compiler" >&5
+echo $ECHO_N "checking what language compliance flags to pass to the C compiler... $ECHO_C" >&6; }
+    complCFLAGS=
+    if test "x$enable_iso_c" != "xno"; then
+	if test "x$GCC" = "xyes"; then
+	case " $CFLAGS " in
+	    *\ \	-ansi\ \	*) ;;
+	    *) complCFLAGS="$complCFLAGS -ansi" ;;
+	esac
+	case " $CFLAGS " in
+	    *\ \	-pedantic\ \	*) ;;
+	    *) complCFLAGS="$complCFLAGS -pedantic" ;;
+	esac
+	fi
+    fi
+    { echo "$as_me:$LINENO: result: $complCFLAGS" >&5
+echo "${ECHO_T}$complCFLAGS" >&6; }
+
+    WARN_CFLAGS="$warning_flags $complCFLAGS"
+
+
 
 { echo "$as_me:$LINENO: checking for X" >&5
 echo $ECHO_N "checking for X... $ECHO_C" >&6; }
@@ -24129,7 +24272,7 @@ fi
 
 fi
 if test -n "$PKG_CONFIG"; then
-	_pkg_min_version=0.7
+	_pkg_min_version=0.16
 	{ echo "$as_me:$LINENO: checking pkg-config is at least version $_pkg_min_version" >&5
 echo $ECHO_N "checking pkg-config is at least version $_pkg_min_version... $ECHO_C" >&6; }
 	if $PKG_CONFIG --atleast-pkgconfig-version $_pkg_min_version; then
@@ -24513,8 +24656,6 @@ fi
 
 
 
-
-
 # Extract the first word of "gconftool-2", so it can be a program name with args.
 set dummy gconftool-2; ac_word=$2
 { echo "$as_me:$LINENO: checking for $ac_word" >&5
@@ -24613,7 +24754,6 @@ else
   GCONF_SCHEMAS_INSTALL_TRUE='#'
   GCONF_SCHEMAS_INSTALL_FALSE=
 fi
-
 
 
 
@@ -24732,6 +24872,119 @@ fi
 
 
 
+pkg_failed=no
+{ echo "$as_me:$LINENO: checking for XSS_EXTENSION" >&5
+echo $ECHO_N "checking for XSS_EXTENSION... $ECHO_C" >&6; }
+
+if test -n "$PKG_CONFIG"; then
+    if test -n "$XSS_EXTENSION_CFLAGS"; then
+        pkg_cv_XSS_EXTENSION_CFLAGS="$XSS_EXTENSION_CFLAGS"
+    else
+        if test -n "$PKG_CONFIG" && \
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"xscrnsaver\"") >&5
+  ($PKG_CONFIG --exists --print-errors "xscrnsaver") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_XSS_EXTENSION_CFLAGS=`$PKG_CONFIG --cflags "xscrnsaver" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+    fi
+else
+	pkg_failed=untried
+fi
+if test -n "$PKG_CONFIG"; then
+    if test -n "$XSS_EXTENSION_LIBS"; then
+        pkg_cv_XSS_EXTENSION_LIBS="$XSS_EXTENSION_LIBS"
+    else
+        if test -n "$PKG_CONFIG" && \
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"xscrnsaver\"") >&5
+  ($PKG_CONFIG --exists --print-errors "xscrnsaver") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_XSS_EXTENSION_LIBS=`$PKG_CONFIG --libs "xscrnsaver" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+    fi
+else
+	pkg_failed=untried
+fi
+
+
+
+if test $pkg_failed = yes; then
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        XSS_EXTENSION_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "xscrnsaver"`
+        else
+	        XSS_EXTENSION_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "xscrnsaver"`
+        fi
+	# Put the nasty error message in config.log where it belongs
+	echo "$XSS_EXTENSION_PKG_ERRORS" >&5
+
+	{ { echo "$as_me:$LINENO: error: Package requirements (xscrnsaver) were not met:
+
+$XSS_EXTENSION_PKG_ERRORS
+
+Consider adjusting the PKG_CONFIG_PATH environment variable if you
+installed software in a non-standard prefix.
+
+Alternatively, you may set the environment variables XSS_EXTENSION_CFLAGS
+and XSS_EXTENSION_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&5
+echo "$as_me: error: Package requirements (xscrnsaver) were not met:
+
+$XSS_EXTENSION_PKG_ERRORS
+
+Consider adjusting the PKG_CONFIG_PATH environment variable if you
+installed software in a non-standard prefix.
+
+Alternatively, you may set the environment variables XSS_EXTENSION_CFLAGS
+and XSS_EXTENSION_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&2;}
+   { (exit 1); exit 1; }; }
+elif test $pkg_failed = untried; then
+	{ { echo "$as_me:$LINENO: error: The pkg-config script could not be found or is too old.  Make sure it
+is in your PATH or set the PKG_CONFIG environment variable to the full
+path to pkg-config.
+
+Alternatively, you may set the environment variables XSS_EXTENSION_CFLAGS
+and XSS_EXTENSION_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+
+To get pkg-config, see <http://pkg-config.freedesktop.org/>.
+See \`config.log' for more details." >&5
+echo "$as_me: error: The pkg-config script could not be found or is too old.  Make sure it
+is in your PATH or set the PKG_CONFIG environment variable to the full
+path to pkg-config.
+
+Alternatively, you may set the environment variables XSS_EXTENSION_CFLAGS
+and XSS_EXTENSION_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+
+To get pkg-config, see <http://pkg-config.freedesktop.org/>.
+See \`config.log' for more details." >&2;}
+   { (exit 1); exit 1; }; }
+else
+	XSS_EXTENSION_CFLAGS=$pkg_cv_XSS_EXTENSION_CFLAGS
+	XSS_EXTENSION_LIBS=$pkg_cv_XSS_EXTENSION_LIBS
+        { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+	:
+fi
+
+
+
 
 
 
@@ -24845,7 +25098,6 @@ else
 echo "${ECHO_T}yes" >&6; }
 	:
 fi
-
 
 
 
@@ -29790,6 +30042,7 @@ MAINTAINER_MODE_FALSE!$MAINTAINER_MODE_FALSE$ac_delim
 MAINT!$MAINT$ac_delim
 YACC!$YACC$ac_delim
 YFLAGS!$YFLAGS$ac_delim
+WARN_CFLAGS!$WARN_CFLAGS$ac_delim
 XMKMF!$XMKMF$ac_delim
 X_CFLAGS!$X_CFLAGS$ac_delim
 X_PRE_LIBS!$X_PRE_LIBS$ac_delim
@@ -29816,6 +30069,8 @@ GCONF_SCHEMAS_INSTALL_TRUE!$GCONF_SCHEMAS_INSTALL_TRUE$ac_delim
 GCONF_SCHEMAS_INSTALL_FALSE!$GCONF_SCHEMAS_INSTALL_FALSE$ac_delim
 LIBQOF_CFLAGS!$LIBQOF_CFLAGS$ac_delim
 LIBQOF_LIBS!$LIBQOF_LIBS$ac_delim
+XSS_EXTENSION_CFLAGS!$XSS_EXTENSION_CFLAGS$ac_delim
+XSS_EXTENSION_LIBS!$XSS_EXTENSION_LIBS$ac_delim
 LIBDBUS_CFLAGS!$LIBDBUS_CFLAGS$ac_delim
 LIBDBUS_LIBS!$LIBDBUS_LIBS$ac_delim
 LIBGNOMEVFS_CFLAGS!$LIBGNOMEVFS_CFLAGS$ac_delim
@@ -29847,7 +30102,7 @@ gnomeutilslocaledir!$gnomeutilslocaledir$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 90; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 93; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
@@ -30503,6 +30758,8 @@ echo "LIBQOF_LIBS : $LIBQOF_LIBS"
 echo "LIBQOF_CFLAGS : $LIBQOF_CFLAGS"
 echo "LIBDBUS_LIBS : $LIBDBUS_LIBS"
 echo "LIBDBUS_CFLAGS : $LIBDBUS_CFLAGS"
+echo "XSS_EXTENSION_CFLAGS : $XSS_EXTENSION_CFLAGS"
+echo "XSS_EXTENSION_LIBS : $XSS_EXTENSION_LIBS"
 echo ""
 
 echo "prefix : $prefix"
